/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0b1326",
        surface: "#0b1326",
        "surface-hover": "hsl(var(--hue, 250), 20%, 18%)",
        "surface-variant": "#2d3449",
        "surface-tint": "#ffb59d",
        "surface-dim": "#0b1326",
        "surface-bright": "#31394d",
        "surface-container-lowest": "#060e20",
        "surface-container-low": "#131b2e",
        "surface-container": "#171f33",
        "surface-container-high": "#222a3d",
        "surface-container-highest": "#2d3449",
        border: "hsl(var(--hue, 250), 20%, 18%)",
        outline: "#a98a80",
        "outline-variant": "#594139",
        primary: "#ffb59d",
        "primary-container": "#ff6b35",
        "primary-fixed": "#ffdbd0",
        "primary-fixed-dim": "#ffb59d",
        "on-primary": "#5d1900",
        "on-primary-container": "#5f1900",
        "on-primary-fixed": "#390c00",
        "on-primary-fixed-variant": "#832600",
        "inverse-primary": "#ab3500",
        secondary: "#4edea3",
        "secondary-container": "#00a572",
        "secondary-fixed": "#6ffbbe",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary": "#003824",
        "on-secondary-container": "#00311f",
        "on-secondary-fixed": "#002113",
        "on-secondary-fixed-variant": "#005236",
        tertiary: "#59d5fb",
        "tertiary-container": "#00a7cb",
        "tertiary-fixed": "#b5ebff",
        "tertiary-fixed-dim": "#59d5fb",
        "on-tertiary": "#003543",
        "on-tertiary-container": "#003744",
        "on-tertiary-fixed-variant": "#004e60",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "on-background": "#dae2fd",
        "on-surface": "#dae2fd",
        "on-surface-variant": "#e1bfb5",
        "inverse-on-surface": "#283044",
        accent: "hsl(var(--hue, 250), 80%, 65%)",
        "accent-hover": "hsl(var(--hue, 250), 80%, 75%)",
        accentglow: "var(--accent-glow)",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Be Vietnam Pro", "sans-serif"],
        label: ["Be Vietnam Pro", "sans-serif"],
      },
    },
  },
  plugins: [],
}
